version: '2'

services:
  bot:
    # image: 'stoutyalex/sheev-bot:latest'
    build: .
    depends_on:
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/sheev-bot

  db:
    image: mongo
    ports:
      - '27017:27017'
